Docker env fix
ripples/lecture-viewer pull request #35
Opened 2016-09-18 20:58 UTC by dylanfischler

The `.env` file is automatically exposed to Docker globally, no need to explicitly set it in `docker-compose.yml`. This change fixes the issue with explicitly loading `lecture-viewer.env`.

2016-09-18 21:51 UTC, dylanfischler commented
Closing until I can confirm this is a stable change

2016-09-20 03:16 UTC, Cheyans requested changes

2016-09-20 03:16 UTC, Cheyans commented on .env
> +HOST_MEDIA_DIR=~/media/lecture-viewer
We need to leave this at the root level, according to the capture software the media will be dumped to `/media`

2016-09-20 03:22 UTC, Cheyans approved these changes

2016-09-20 03:25 UTC, Cheyans commented
Closes #11

2016-09-22 03:27 UTC, merged